<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\OrganizationUnit;

class OrganizationUnitsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $units = [
            [
                'organization_id' => 1,
                'name' => 'Youth Wing',
                'code' => 'YW-001',
                'description' => 'Youth ministry and activities',
                'parent_unit_id' => null,
                'is_active' => true,
                'unit_type' => 'Ministry',
                'department' => 'Youth',
                'community' => 'Youth Community',
                'ministry_committee' => 'Youth Committee',
                'administrative_office' => 'Youth Office',
                'unit_head' => 1,
                'assistant_leader' => 2,
                'leadership_committee' => json_encode(['John Doe', 'Jane Smith']),
                'appointment_dates' => '2022-01-01 to 2024-01-01',
                'reporting_line' => 'Senior Pastor',
                'mission' => 'Empower youth for leadership.',
                'objectives' => 'Mentorship, outreach, discipleship.',
                'activities' => 'Weekly meetings, community service.',
                'target_audience' => 'Youth ages 13-25',
                'official_email' => 'youth@church.org',
                'phone_contact' => '+1234567890',
                'physical_location' => 'Youth Hall, Main Campus',
                'website' => 'https://youth.church.org',
                'social_links' => 'facebook.com/youthwing',
                'unit_category' => 'Faith',
                'faith_based' => true,
                'socio_economic' => false,
                'support_services' => false,
                'operational_status' => 'active',
                'date_established' => '2010-06-15',
                'membership_type' => 'Open',
                'membership_eligibility' => 'Youth members',
                'membership_capacity' => 100,
                'join_requests_enabled' => true,
                'recurring_programs' => 'Friday Fellowship',
                'event_schedule' => 'Every Friday 6pm',
                'promotion_permissions' => 'Leaders only',
                'resource_access_requirements' => 'Active member',
                'showcase_permissions' => 'All members',
                'product_categories_allowed' => 'Books, T-shirts',
                'approval_workflow' => 'Committee approval',
                'commission_structure' => '10% to ministry',
                'unit_roles' => json_encode(['Leader', 'Member', 'Mentor']),
            ],
            [
                'organization_id' => 1,
                'name' => 'Mothers’ Union',
                'code' => 'MU-001',
                'description' => 'Mothers’ Union and women activities',
                'parent_unit_id' => null,
                'is_active' => true,
                'unit_type' => 'Ministry',
                'department' => 'Women',
                'community' => 'Women Community',
                'ministry_committee' => 'Mothers’ Union Committee',
                'administrative_office' => 'Women Office',
                'unit_head' => 3,
                'assistant_leader' => 4,
                'leadership_committee' => json_encode(['Mary Johnson', 'Grace Lee']),
                'appointment_dates' => '2021-01-01 to 2023-12-31',
                'reporting_line' => 'Women Pastor',
                'mission' => 'Support and empower women.',
                'objectives' => 'Fellowship, support, outreach.',
                'activities' => 'Monthly meetings, charity events.',
                'target_audience' => 'Women ages 18+',
                'official_email' => 'mothers@church.org',
                'phone_contact' => '+1234567891',
                'physical_location' => 'Women Hall, Main Campus',
                'website' => 'https://mothers.church.org',
                'social_links' => 'facebook.com/mothersunion',
                'unit_category' => 'Faith',
                'faith_based' => true,
                'socio_economic' => true,
                'support_services' => false,
                'operational_status' => 'active',
                'date_established' => '2005-03-10',
                'membership_type' => 'Open',
                'membership_eligibility' => 'Women members',
                'membership_capacity' => 80,
                'join_requests_enabled' => true,
                'recurring_programs' => 'Monthly Fellowship',
                'event_schedule' => 'First Saturday each month',
                'promotion_permissions' => 'Committee only',
                'resource_access_requirements' => 'Active member',
                'showcase_permissions' => 'Committee',
                'product_categories_allowed' => 'Crafts, Books',
                'approval_workflow' => 'Committee approval',
                'commission_structure' => '15% to ministry',
                'unit_roles' => json_encode(['Leader', 'Member', 'Supporter']),
            ],
            [
                'organization_id' => 1,
                'name' => 'Media Ministry',
                'code' => 'MM-001',
                'description' => 'Media and communications',
                'parent_unit_id' => null,
                'is_active' => true,
                'unit_type' => 'Ministry',
                'department' => 'Media',
                'community' => 'Media Community',
                'ministry_committee' => 'Media Committee',
                'administrative_office' => 'Media Office',
                'unit_head' => 5,
                'assistant_leader' => 6,
                'leadership_committee' => json_encode(['Paul Media', 'Sarah Tech']),
                'appointment_dates' => '2020-05-01 to 2022-05-01',
                'reporting_line' => 'Media Pastor',
                'mission' => 'Spread the message through media.',
                'objectives' => 'Broadcast, outreach, training.',
                'activities' => 'Live streaming, workshops.',
                'target_audience' => 'All ages',
                'official_email' => 'media@church.org',
                'phone_contact' => '+1234567892',
                'physical_location' => 'Media Room, Main Campus',
                'website' => 'https://media.church.org',
                'social_links' => 'facebook.com/mediaministry',
                'unit_category' => 'Support',
                'faith_based' => false,
                'socio_economic' => false,
                'support_services' => true,
                'operational_status' => 'active',
                'date_established' => '2015-09-20',
                'membership_type' => 'Open',
                'membership_eligibility' => 'Media team',
                'membership_capacity' => 30,
                'join_requests_enabled' => false,
                'recurring_programs' => 'Weekly Broadcast',
                'event_schedule' => 'Every Sunday 10am',
                'promotion_permissions' => 'Leaders only',
                'resource_access_requirements' => 'Media member',
                'showcase_permissions' => 'All members',
                'product_categories_allowed' => 'Media, Tech',
                'approval_workflow' => 'Head approval',
                'commission_structure' => '5% to ministry',
                'unit_roles' => json_encode(['Leader', 'Member', 'Technician']),
            ],
        ];

        foreach ($units as $unit) {
            OrganizationUnit::create($unit);
        }
    }
}
